run_name: ""
seed: 123456789
num_classes : 6
lr: 0.001
epochs: 30
loss_name: "focal"
loss:
  focal_gamma: 2.0
  focal_reduction: "mean"

data:
  root: "data/processed/classification"
  num_workers: 12
  batch_size : 256
  sampling: "default"
  normalization:
    enabled: true
    mean: [0.4291, 0.5388, 0.3654]
    std: [0.1859, 0.2121, 0.1966]

class_names:
  - bud
  - flower
  - green
  - pink
  - purple
  - blue
