defaults:
  - base_config
  - _self_

experiment:
  name: "dummy-exp"
  run_name: "dummy-run"
  tracking_uri: "experiments/mlflow.db"
  artifact_location: "experiments"

seed: 123456789
num_classes : 6
lr: 1e-3
epochs: 1

loss:
  name: "cross-entropy"
  focal_gamma: null
  focal_reduction: null

data:
  root: "data/processed/classification-expanded-boxes"
  num_workers: 12
  batch_size : 256
  sampling: "default"
  normalization:
    # mean: [0.3994, 0.5100, 0.3541]
    # std: [0.1831, 0.2149, 0.2105]
  augmentation:
    # - _target_: torchvision.transforms.v2.RandomHorizontalFlip
      # p: 0.8
    # - _target_: torchvision.transforms.v2.RandomVerticalFlip
      # p: 0.8
    # - _target_: torchvision.transforms.v2.RandomRotation
      # degrees: 10
    # - _target_: torchvision.transforms.v2.ColorJitter
      # brightness: 0.05
      # contrast: 0.05
      # saturation: 0.01

class_names:
  - bud
  - flower
  - green
  - pink
  - purple
  - blue