defaults:
  - base_config
  - _self_

experiment:
  name: "hydra-experiment"
  run_name: "run1"
  tracking_uri: "experiments/mlflow.db"
  artifact_location: "experiments"

seed: 123456789
epochs: 2
data:
  root: "data/processed/classification-expanded-boxes"
  num_workers: 12
  batch_size : 256
  sampling: "default"
  normalization:
    # mean: [0.3994, 0.5100, 0.3541]
    # std: [0.1831, 0.2149, 0.2105]
  augmentation:
    # - _target_: torchvision.transforms.v2.RandomHorizontalFlip
      # p: 0.8
    # - _target_: torchvision.transforms.v2.RandomVerticalFlip
      # p: 0.8
    # - _target_: torchvision.transforms.v2.RandomRotation
      # degrees: 10
    # - _target_: torchvision.transforms.v2.ColorJitter
      # brightness: 0.05
      # contrast: 0.05
      # saturation: 0.01

model:
  name: "resnet18"
  num_classes: 6
  pretrained: true
  default_resnet_downsize: true

optimizer:
  name: "adamw"
  lr: 1e-4
  weight_decay: 0
  betas:
  momentum:
  nesterov:

scheduler:
  # name: ""
  # T_max:
  # eta_min:
  # step_size:
  # gamma:
  # factor:
  # last_epoch:

loss:
  name: "cross-entropy"
  focal_gamma: null
  focal_reduction: null

class_names:
  - bud
  - flower
  - green
  - pink
  - purple
  - blue